[project]
name = "course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.32.0",
    "python-frontmatter",
    "requests",
    "tqdm",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
